version: '3.8'
services:
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: MoneyManageDB
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
